name: Deploy Portfolio

on:
  push:
    branches: [main]

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install, build, and upload
        uses: withastro/action@v1

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
        with:
          path: ./dist
